"""
Agent State & Output Schemas — Pydantic models and TypedDict for strict state typing.

Defines the LangGraph state schema (AgentState) and the structured output model
(ArchitectOutput) that constrains the Architect agent's response format.
"""

from typing import TypedDict

from pydantic import BaseModel, Field


class AgentState(TypedDict):
    """
    LangGraph state schema — passed between all nodes in the graph.

    Enforces strict typing to prevent malformed payloads between nodes.
    """

    # ── User Input ──
    user_prompt: str
    """The original infrastructure request (e.g., 'Deploy a secure EKS cluster')."""

    # ── RAG Context ──
    rag_context: str
    """Retrieved text snippets from Terraform AWS documentation."""

    # ── Architect Output ──
    current_code: str
    """The raw HCL payload generated by the Cloud Architect agent."""

    architect_reflection: str
    """The LLM's step-by-step reasoning for the current code iteration."""

    # ── Agent Critiques ──
    security_critique: str
    """Hostile feedback and red-team findings from the SecOps Adversary Agent."""

    finops_critique: str
    """Budget optimization feedback from the FinOps Cost Agent."""

    # ── Gatekeeper Results ──
    linter_logs: str
    """Raw stderr/stdout and JSON crash reports from CLI tools."""

    security_score: float
    """0-100 quantitative score calculated from Checkov's output."""

    monthly_cost: float
    """Projected monthly USD cost parsed from Infracost."""

    # ── Pipeline Control ──
    iteration_count: int
    """Failsafe counter to prevent infinite API billing loops (max 5)."""

    terraform_valid: bool
    """Whether terraform validate passed (exit_code == 0)."""


class ArchitectOutput(BaseModel):
    """
    Structured output model for the Cloud Architect agent.

    Enforced via .with_structured_output() to eliminate fragile regex parsing.
    The agent MUST return this exact schema — no markdown, no conversational text.
    """

    thought_process: str = Field(
        description=(
            "Step-by-step reasoning on how to build this architecture, "
            "or a detailed plan on how to fix the specific errors found in "
            "the previous linter_logs."
        )
    )
    terraform_code: str = Field(
        description=(
            "The complete, raw, syntactically valid HCL code. "
            "Do not include markdown formatting (no ```hcl blocks). "
            "This will be written directly to a .tf file."
        )
    )


class SecOpsOutput(BaseModel):
    """Structured output for the SecOps Adversary agent."""

    security_issues: str = Field(
        description=(
            "Detailed, actionable, line-number-specific security findings. "
            "Include threat severity (CRITICAL/HIGH/MEDIUM/LOW) for each issue."
        )
    )
    risk_summary: str = Field(
        description="One-paragraph executive summary of the overall security posture."
    )


class FinOpsOutput(BaseModel):
    """Structured output for the FinOps Cost agent."""

    cost_optimizations: str = Field(
        description=(
            "Specific, actionable cost optimization recommendations. "
            "Include estimated savings percentages where possible."
        )
    )
    cost_summary: str = Field(
        description="One-paragraph executive summary of the cost profile and key recommendations."
    )
